apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - name: discovery
          env:
            - name: PILOT_TRACE_SAMPLING
              value: "100"
            - name: ZIPKIN_ADDRESS
              value: "tempo.observability.svc.cluster.local:9411"