apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        owner: sre
        version: v1
    spec:
      containers:
        - name: service-a
          image: node:20-alpine
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Service A"
