apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    owner: sre-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
      owner: sre-team
  template:
    metadata:
      labels:
        app: service-a
        owner: sre-team
        version: v1
      annotations:
        trivy.io/severity: "LOW"
    spec:
      containers:
        - name: service-a
          image: kennethreitz/httpbin       # ✅ changed image
          ports:
            - containerPort: 80            # ✅ httpbin listens on 80
          env:
            - name: TARGET
              value: "Service A v1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            capabilities:
              drop: ["ALL"]
