apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v2
  labels:
    app: service-a
    owner: sre-team
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
      version: v2
  template:
    metadata:
      labels:
        app: service-a
        version: v2
    spec:
      containers:
        - name: service-a
          image: alpine:3.18
          command: ["sh", "-c"]
          args:
            - echo "Starting service A v2"; 
              apk add --no-cache curl; 
              while true; do echo "{\"TARGET\":\"$TARGET\"}" | nc -l -p 8080 -q 1; done
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Service A v2"
