apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v2
  namespace: default
  labels:
    app: service-a
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
      version: v2
  template:
    metadata:
      labels:
        app: service-a
        version: v2
    spec:
      containers:
        - name: service-a
          image: mccutchen/go-httpbin
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Service A v2"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
