apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service-a
  namespace: default
spec:
  host: service-a
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1
