apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-a
spec:
  hosts:
    - service-a
    - "*"
  gateways:
    - mesh
    - sre-gateway
  http:
    - match:
        - uri:
            prefix: /service-a
      route:
        - destination:
            host: service-a
            subset: v1
            port:
              number: 80
          weight: 50
        - destination:
            host: service-a
            subset: v2
            port:
              number: 80
          weight: 50
