apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
        owner: sre
        version: v1
      annotations:
        trivy.io/severity: "LOW"
    spec:
      containers:
        - name: service-c
          image: jaegertracing/example-hotrod
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Service C"
