apiVersion: v1
kind: Pod
metadata:
  name: debug-tools
  labels:
    istio-injection: enabled
spec:
  containers:
  - name: debug-tools
    image: curlimages/curl:8.14.1
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
