apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
  labels:
    app: debug
spec:
  containers:
  - name: debug
    image: busybox:1.36
    command: ["sh"]
    stdin: true
    tty: true
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
  restartPolicy: Never
