# promtail-values.yaml

image:
  repository: cgr.dev/chainguard/promtail
  tag: v2.9.0             # Fixed version, not 'latest'
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: promtail

rbac:
  create: true

daemonset:
  podAnnotations:
    kyverno-disable-block-high-cve: "true"  # skip block-high-cve policy

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Optional: tolerations and nodeSelector
tolerations:
  - key: "node-role.kubernetes.io/monitoring"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector:
  monitoring: "true"

# Optional: Promtail config
config:
  lokiAddress: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
  extraScrapeConfigs: []
