apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno
  namespace: kyverno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyverno
  template:
    metadata:
      labels:
        app: kyverno
    spec:
      containers:
        - name: kyverno
          image: ghcr.io/kyverno/kyverno:v1.11.0