image:
  repository: cgr.dev/chainguard/promtail
  tag: v2.9.0        # Use a specific version instead of 'latest'
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: promtail

rbac:
  create: true

daemonset:
  podLabels:
    kyverno-disable-block-high-cve: "true"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
