image:
  repository: cgr.dev/chainguard/promtail
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: promtail

rbac:
  create: true

daemonset:
  podLabels:
    kyverno-disable-block-high-cve: "true"
