# Promtail values override

# Use a safe image (Kyverno will block images with high CVEs)
image:
  repository: grafana/promtail
  tag: 2.9.3   # matches chart 6.15.5

# Service settings
service:
  type: ClusterIP
  port: 3101

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true

# RBAC
rbac:
  create: true

# Resources (tune based on your cluster capacity)
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Tolerations to run on all nodes (like fluentd/daemonset)
tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists

# Log targets
config:
  server:
    http_listen_port: 3101
    grpc_listen_port: 0

  positions:
    filename: /run/promtail/positions.yaml

  clients:
    - url: http://loki.monitoring:3100/loki/api/v1/push

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: __host__
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
