image:
  repository: cgr.dev/chainguard/promtail
  tag: latest

podAnnotations:
  trivy.io/severity: "HIGH"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

loki:
  serviceName: loki-gateway
