image:
  repository: grafana/promtail
  tag: 3.1.1   # or latest stable version

podAnnotations:
  trivy.io/severity: "HIGH"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

loki:
  serviceName: loki-gateway
