# promtail-values.yaml

image:
  repository: grafana/promtail
  tag: 3.0.0   # override to avoid HIGH CVEs flagged by Kyverno
  pullPolicy: IfNotPresent

# Deployment namespace
namespaceOverride: monitoring

# Service account
serviceAccount:
  create: true
  name: promtail

# RBAC
rbac:
  create: true

# Service
service:
  enabled: true
  type: ClusterIP
  port: 3101

# Promtail configuration
config:
  clients:
    - url: http://loki:3100/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

  scrape_configs:
    - job_name: system
      static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log
