apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-scan
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trivy
              image: aquasec/trivy:latest
              args: ["image", "--severity", "HIGH", "ghcr.io/knative/helloworld-go"]
          restartPolicy: OnFailure