adminUser: admin
adminPassword: prom-operator

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server

dashboards:
  istio:
    istio-dashboard:
      gnetId: 7636
      revision: 1
      datasource: Prometheus


service:
  type: ClusterIP


resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m