apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: default
  labels:
    app: load-generator
    owner: sre-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
        owner: sre-team
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: hey
        image: busybox:1.36
        command: ["sh", "-c"]
        args:
          - |
            echo "Starting load test...";
            while true; do
              wget -qO- http://service-a.default.svc.cluster.local:8080/metrics;
              sleep 1;
            done
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
