apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: default
  labels:
    app: load-generator
    owner: sre-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
        owner: sre-team
    spec:
      containers:
      - name: hey
        image: ghcr.io/rakyll/hey:v0.1.4   # or any other load generator image
        command: ["hey"]
        args: ["-z", "30s", "-q", "10", "http://service-a.default.svc.cluster.local:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      # Deployment default: restartPolicy: Always (remove explicit restartPolicy)
