apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: default
  labels:
    app: load-generator
    owner: sre-team   # replace with your name/team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
        owner: sre-team
    spec:
      containers:
      - name: hey
        image: ghcr.io/rakyll/hey:latest
        command: ["hey"]
        args: ["-z", "30s", "-q", "10", "http://service-a.default.svc.cluster.local"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
