apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: default
  labels:
    app: load-generator
    owner: sre-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
        owner: sre-team
    spec:
      containers:
      - name: hey
        # Replaced with a public image to avoid pull issues
        image: busybox:1.36
        command: ["sh", "-c"]
        args: ["echo 'Load test running'; sleep 30"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      restartPolicy: Never
