apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bhavesh1326/eks-sre-gitops   # your Git repo
    path: observability/promtail                              # path to chart folder
    targetRevision: main                                      # branch
    helm:
      valueFiles:
        - values.yaml                                # relative to path
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
