apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.16.6       # Use a chart version Kyverno allows
    helm:
      values: |
        image:
          repository: cgr.dev/chainguard/promtail
          tag: latest
          pullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
