apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
    owner: sre-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
      owner: sre-team
  template:
    metadata:
      labels:
        app: service-b
        owner: sre-team
        version: v1
      annotations:
        trivy.io/severity: "LOW"
    spec:
      containers:
        - name: service-b
          image: hashicorp/http-echo
          args:
            - "-listen=:8080"
            - "-text=Hello from Service B"
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Service B"
          resources:   # ✅ required by Kyverno
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:   # ✅ required by Kyverno
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            capabilities:
              drop: ["ALL"]
