apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        owner: sre
        version: v1
    spec:
      containers:
        - name: service-b
          image: node:20-bullseye
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Service B"
