apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-b
spec:
  hosts:
    - "*"
  gateways:
    - sre-gateway
  http:
    - match:
        - uri:
            prefix: /service-b
      route:
        - destination:
            host: service-b
            port:
              number: 80