name: Deploy Falco Secret

on:
  push:
    paths:
      - falco/**   # Trigger only when falco folder changes

jobs:
  create-falco-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create Falco Slack Secret
        run: |
          kubectl create namespace falco --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic falco-slack \
            --from-literal=webhookurl="${{ secrets.FALCO_SLACK_WEBHOOK }}" \
            -n falco --dry-run=client -o yaml | kubectl apply -f -
