name: Deploy Falco Secret

on:
  push:
    paths:
      - falco/**

jobs:
  create-falco-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Falco Slack Secret
        run: |
          kubectl create namespace falco --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic falco-slack \
            --from-literal=webhookurl=${{ secrets.FALCO_SLACK_WEBHOOK }} \
            -n falco --dry-run=client -o yaml | kubectl apply -f -
