name: Gitleaks Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""       # default config
          redact: true          # hide secrets in logs
          fail-on-error: false  # do not fail the workflow if leaks found
