name: Gitleaks Secret Scan

# Trigger on push and pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run Gitleaks v2
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          redact: true        # Redact secrets in logs
          failOnError: true  # Fail job if leaks are found
